### ISSUE TITLE
5.0的手机打开首页妹子图片的时候crash

### ISSUE THREAD

**Issue by coolegos** [HotBitmapGG/MoeQuest#4]
```
07-18 20:51:50.945 24683-24683/com.hotbitmapgg.moequest E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.hotbitmapgg.moequest, PID: 24683
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hotbitmapgg.moequest/com.hotbitmapgg.moequest.ui.activity.GankMeiziPageActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.View.getAlpha()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
at android.app.ActivityThread.access$800(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:155)
at android.app.ActivityThread.main(ActivityThread.java:5727)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

没找到哪里有调用getAlpha()，4.4.4的手机没出现

**Comment by HotBitmapGG** [comment]
我用5.0的手机看了下 好像没有崩溃啊，而且这个报错怎么这么奇怪

**Comment by HotBitmapGG** [comment]
这个问题我跟了下，是界面共享元素动画的问题，但是不知道到底是哪里报的错，debug没有什么结果，目前只能把大于API22才使用共享元素动画了，在5.1，6.0上还是正常使用的,5.0就崩溃,这个具体我在研究下.

**Comment by Caij** [comment]
你好 我遇到同样的问题。 我的APP线上统计vivo的5.0会闪退 其他型号手机没有闪退日志。 @coolegos   你的手机是什么型号？ @HotBitmapGG  除了提升版本 有其他更好的办法吗？
